# Generated by Django 5.2.6 on 2025-09-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogs_author_blog'),
        ('comment', '0003_comment_delete_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
