# Generated by Django 5.2.6 on 2025-09-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_delete_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='public/blogs/'),
        ),
    ]
